export const PLAYBOOK_TEMPLATES = [
  {
    id: "phishing-email-triage",
    name: "Phishing Email Triage",
    category: "Email Security",
    severity: "High",
    difficulty: "Intermediate",
    estimatedTime: "8-12 min",
    maturity: "Production Ready",
    riskScore: 82,
    approvalRequired: false,
    demoReady: true,
    recommendedDemo: true,
    description:
      "Investigate suspicious email reports, extract indicators, enrich IOCs, check reputation, and prepare analyst response.",
    tags: ["phishing", "email", "ioc", "triage"],
    connectors: ["Email Gateway", "VirusTotal", "AbuseIPDB", "SIEM"],
    mitre: [
      { id: "T1566", name: "Phishing" },
      { id: "T1204", name: "User Execution" },
      { id: "T1059", name: "Command and Scripting Interpreter" },
    ],
    quality: [
      "Best for FYP demo",
      "Clear incident workflow",
      "Easy to explain",
      "Low destructive risk",
    ],
    steps: [
      {
        step_order: 1,
        step_type: "Trigger",
        name: "Suspicious Email Alert",
        action_key: "email.trigger",
        connector_name: "Email Gateway",
        config: { source: "reported_email" },
        condition: {},
      },
      {
        step_order: 2,
        step_type: "Action",
        name: "Extract Indicators",
        action_key: "email.extract_indicators",
        connector_name: "SOAR Engine",
        config: { extract_urls: true, extract_ips: true, extract_hashes: true },
        condition: {},
      },
      {
        step_order: 3,
        step_type: "Action",
        name: "Reputation Lookup",
        action_key: "threatintel.reputation_lookup",
        connector_name: "VirusTotal",
        config: { scan_urls: true, scan_hashes: true },
        condition: {},
      },
      {
        step_order: 4,
        step_type: "Decision",
        name: "Malicious IOC Found?",
        action_key: "decision.malicious_ioc",
        connector_name: "SOAR Engine",
        config: {},
        condition: { field: "risk_score", operator: ">=", value: 70 },
      },
      {
        step_order: 5,
        step_type: "Action",
        name: "Create Incident Summary",
        action_key: "incident.create_summary",
        connector_name: "SOAR Engine",
        config: { include_iocs: true, include_recommendations: true },
        condition: {},
      },
      {
        step_order: 6,
        step_type: "Action",
        name: "Notify SOC Analyst",
        action_key: "notification.soc_analyst",
        connector_name: "Webhook",
        config: { priority: "high" },
        condition: {},
      },
    ],
  },
  {
    id: "malware-endpoint-isolation",
    name: "Malware Endpoint Isolation",
    category: "Endpoint Security",
    severity: "Critical",
    difficulty: "Advanced",
    estimatedTime: "10-15 min",
    maturity: "Advanced",
    riskScore: 95,
    approvalRequired: true,
    demoReady: true,
    recommendedDemo: true,
    description:
      "Respond to malware alerts by enriching file indicators, checking endpoint state, isolating host, and collecting evidence.",
    tags: ["malware", "endpoint", "edr", "isolation"],
    connectors: ["Microsoft Defender", "VirusTotal", "SIEM", "Webhook"],
    mitre: [
      { id: "T1204", name: "User Execution" },
      { id: "T1059", name: "Command and Scripting Interpreter" },
      { id: "T1486", name: "Data Encrypted for Impact" },
    ],
    quality: [
      "Strong enterprise use case",
      "Shows containment automation",
      "Requires approval gate",
      "Excellent SOC demo",
    ],
    steps: [
      {
        step_order: 1,
        step_type: "Trigger",
        name: "Malware Detection Alert",
        action_key: "edr.malware_alert",
        connector_name: "Microsoft Defender",
        config: { alert_type: "malware" },
        condition: {},
      },
      {
        step_order: 2,
        step_type: "Action",
        name: "Collect Endpoint Context",
        action_key: "edr.collect_context",
        connector_name: "Microsoft Defender",
        config: { include_process_tree: true, include_user: true },
        condition: {},
      },
      {
        step_order: 3,
        step_type: "Action",
        name: "Hash Reputation Lookup",
        action_key: "threatintel.hash_lookup",
        connector_name: "VirusTotal",
        config: { reputation_required: true },
        condition: {},
      },
      {
        step_order: 4,
        step_type: "Decision",
        name: "Critical Malware Confirmed?",
        action_key: "decision.critical_malware",
        connector_name: "SOAR Engine",
        config: {},
        condition: { field: "malware_confidence", operator: ">=", value: 80 },
      },
      {
        step_order: 5,
        step_type: "Action",
        name: "Isolate Endpoint",
        action_key: "edr.isolate_endpoint",
        connector_name: "Microsoft Defender",
        config: { require_approval: true },
        condition: {},
      },
      {
        step_order: 6,
        step_type: "Action",
        name: "Collect Investigation Package",
        action_key: "edr.collect_investigation_package",
        connector_name: "Microsoft Defender",
        config: { collect_memory: false, collect_artifacts: true },
        condition: {},
      },
      {
        step_order: 7,
        step_type: "Action",
        name: "Notify Incident Commander",
        action_key: "notification.incident_commander",
        connector_name: "Webhook",
        config: { priority: "critical" },
        condition: {},
      },
    ],
  },
  {
    id: "brute-force-investigation",
    name: "Brute Force Investigation",
    category: "Identity Security",
    severity: "High",
    difficulty: "Intermediate",
    estimatedTime: "7-10 min",
    maturity: "Production Ready",
    riskScore: 78,
    approvalRequired: false,
    demoReady: true,
    recommendedDemo: false,
    description:
      "Investigate repeated authentication failures, enrich source IPs, check impacted users, and recommend containment.",
    tags: ["brute-force", "identity", "authentication", "login"],
    connectors: ["SIEM", "AbuseIPDB", "Identity Provider", "Webhook"],
    mitre: [
      { id: "T1110", name: "Brute Force" },
      { id: "T1078", name: "Valid Accounts" },
      { id: "T1090", name: "Proxy" },
    ],
    quality: [
      "Good identity security demo",
      "Easy logs correlation",
      "Useful for SOC workflow",
      "Good MITRE mapping",
    ],
    steps: [
      {
        step_order: 1,
        step_type: "Trigger",
        name: "Failed Login Spike",
        action_key: "siem.failed_login_alert",
        connector_name: "SIEM",
        config: { threshold: 20, window_minutes: 10 },
        condition: {},
      },
      {
        step_order: 2,
        step_type: "Action",
        name: "Extract Source IPs",
        action_key: "siem.extract_source_ips",
        connector_name: "SIEM",
        config: { deduplicate: true },
        condition: {},
      },
      {
        step_order: 3,
        step_type: "Action",
        name: "Check IP Abuse Score",
        action_key: "threatintel.ip_abuse_lookup",
        connector_name: "AbuseIPDB",
        config: { max_age_days: 30 },
        condition: {},
      },
      {
        step_order: 4,
        step_type: "Action",
        name: "Identify Targeted Users",
        action_key: "identity.find_targeted_users",
        connector_name: "Identity Provider",
        config: { include_lockout_status: true },
        condition: {},
      },
      {
        step_order: 5,
        step_type: "Decision",
        name: "High Confidence Attack?",
        action_key: "decision.bruteforce_confidence",
        connector_name: "SOAR Engine",
        config: {},
        condition: { field: "attack_confidence", operator: ">=", value: 75 },
      },
      {
        step_order: 6,
        step_type: "Action",
        name: "Create Analyst Recommendation",
        action_key: "incident.recommend_bruteforce_response",
        connector_name: "SOAR Engine",
        config: { recommend_block: true, recommend_password_reset: true },
        condition: {},
      },
    ],
  },
  {
    id: "suspicious-ip-enrichment",
    name: "Suspicious IP Enrichment",
    category: "Threat Intelligence",
    severity: "Medium",
    difficulty: "Beginner",
    estimatedTime: "3-6 min",
    maturity: "Demo Ready",
    riskScore: 56,
    approvalRequired: false,
    demoReady: true,
    recommendedDemo: true,
    description:
      "Enrich suspicious IP addresses using threat intelligence, geo context, abuse confidence, and SIEM history.",
    tags: ["ioc", "ip", "threat-intel", "enrichment"],
    connectors: ["AbuseIPDB", "VirusTotal", "GeoIP", "SIEM"],
    mitre: [
      { id: "T1595", name: "Active Scanning" },
      { id: "T1090", name: "Proxy" },
      { id: "T1105", name: "Ingress Tool Transfer" },
    ],
    quality: [
      "Fastest demo template",
      "Best for IOC enrichment",
      "Simple workflow",
      "Safe automation",
    ],
    steps: [
      {
        step_order: 1,
        step_type: "Trigger",
        name: "Suspicious IP Submitted",
        action_key: "ioc.ip_submitted",
        connector_name: "SOAR Engine",
        config: { input_type: "ip" },
        condition: {},
      },
      {
        step_order: 2,
        step_type: "Action",
        name: "Abuse Confidence Lookup",
        action_key: "threatintel.abuseipdb_lookup",
        connector_name: "AbuseIPDB",
        config: { include_reports: true },
        condition: {},
      },
      {
        step_order: 3,
        step_type: "Action",
        name: "VirusTotal IP Lookup",
        action_key: "threatintel.virustotal_ip_lookup",
        connector_name: "VirusTotal",
        config: { include_votes: true },
        condition: {},
      },
      {
        step_order: 4,
        step_type: "Action",
        name: "GeoIP Context",
        action_key: "geoip.lookup",
        connector_name: "GeoIP",
        config: { include_asn: true, include_country: true },
        condition: {},
      },
      {
        step_order: 5,
        step_type: "Action",
        name: "Search SIEM History",
        action_key: "siem.search_ioc_history",
        connector_name: "SIEM",
        config: { lookback_days: 7 },
        condition: {},
      },
      {
        step_order: 6,
        step_type: "Action",
        name: "Generate Risk Summary",
        action_key: "threatintel.generate_risk_summary",
        connector_name: "SOAR Engine",
        config: { include_recommendations: true },
        condition: {},
      },
    ],
  },
  {
    id: "data-exfiltration-response",
    name: "Data Exfiltration Response",
    category: "Data Security",
    severity: "Critical",
    difficulty: "Advanced",
    estimatedTime: "15-20 min",
    maturity: "Advanced",
    riskScore: 91,
    approvalRequired: true,
    demoReady: false,
    recommendedDemo: false,
    description:
      "Investigate abnormal outbound traffic, identify user/device context, collect evidence, and recommend containment.",
    tags: ["exfiltration", "data-loss", "network", "incident-response"],
    connectors: ["SIEM", "Firewall", "DLP", "Webhook"],
    mitre: [
      { id: "T1041", name: "Exfiltration Over C2 Channel" },
      { id: "T1020", name: "Automated Exfiltration" },
      { id: "T1567", name: "Exfiltration Over Web Service" },
    ],
    quality: [
      "Advanced enterprise scenario",
      "Good for senior demo",
      "Requires DLP context",
      "Strong incident response value",
    ],
    steps: [
      {
        step_order: 1,
        step_type: "Trigger",
        name: "Abnormal Outbound Traffic Alert",
        action_key: "siem.exfiltration_alert",
        connector_name: "SIEM",
        config: { alert_type: "data_exfiltration" },
        condition: {},
      },
      {
        step_order: 2,
        step_type: "Action",
        name: "Collect Network Flow Evidence",
        action_key: "network.collect_flow_evidence",
        connector_name: "Firewall",
        config: { lookback_hours: 24 },
        condition: {},
      },
      {
        step_order: 3,
        step_type: "Action",
        name: "Identify User and Asset",
        action_key: "siem.identify_user_asset",
        connector_name: "SIEM",
        config: { correlate_identity: true },
        condition: {},
      },
      {
        step_order: 4,
        step_type: "Action",
        name: "Check DLP Events",
        action_key: "dlp.search_events",
        connector_name: "DLP",
        config: { include_sensitive_labels: true },
        condition: {},
      },
      {
        step_order: 5,
        step_type: "Decision",
        name: "Confirmed Sensitive Data Movement?",
        action_key: "decision.exfil_confirmed",
        connector_name: "SOAR Engine",
        config: {},
        condition: { field: "exfil_confidence", operator: ">=", value: 80 },
      },
      {
        step_order: 6,
        step_type: "Action",
        name: "Recommend Containment",
        action_key: "incident.recommend_exfil_containment",
        connector_name: "SOAR Engine",
        config: { recommend_block_destination: true },
        condition: {},
      },
      {
        step_order: 7,
        step_type: "Action",
        name: "Notify SOC Lead",
        action_key: "notification.soc_lead",
        connector_name: "Webhook",
        config: { priority: "critical" },
        condition: {},
      },
    ],
  },
  {
    id: "ransomware-initial-response",
    name: "Ransomware Initial Response",
    category: "Incident Response",
    severity: "Critical",
    difficulty: "Advanced",
    estimatedTime: "12-18 min",
    maturity: "Advanced",
    riskScore: 98,
    approvalRequired: true,
    demoReady: true,
    recommendedDemo: true,
    description:
      "Perform initial ransomware triage, identify impacted endpoints, collect indicators, isolate hosts, and alert leadership.",
    tags: ["ransomware", "critical", "containment", "forensics"],
    connectors: ["Microsoft Defender", "SIEM", "VirusTotal", "Webhook"],
    mitre: [
      { id: "T1486", name: "Data Encrypted for Impact" },
      { id: "T1490", name: "Inhibit System Recovery" },
      { id: "T1083", name: "File and Directory Discovery" },
    ],
    quality: [
      "Most impressive FYP demo",
      "Critical incident response",
      "Shows approval workflow",
      "Strong executive impact",
    ],
    steps: [
      {
        step_order: 1,
        step_type: "Trigger",
        name: "Ransomware Behavior Alert",
        action_key: "edr.ransomware_alert",
        connector_name: "Microsoft Defender",
        config: { alert_type: "ransomware" },
        condition: {},
      },
      {
        step_order: 2,
        step_type: "Action",
        name: "Identify Impacted Hosts",
        action_key: "edr.identify_impacted_hosts",
        connector_name: "Microsoft Defender",
        config: { include_lateral_movement: true },
        condition: {},
      },
      {
        step_order: 3,
        step_type: "Action",
        name: "Collect Ransomware Indicators",
        action_key: "edr.collect_ransomware_iocs",
        connector_name: "Microsoft Defender",
        config: { include_hashes: true, include_file_paths: true },
        condition: {},
      },
      {
        step_order: 4,
        step_type: "Action",
        name: "Enrich File Hashes",
        action_key: "threatintel.hash_lookup",
        connector_name: "VirusTotal",
        config: { include_malware_family: true },
        condition: {},
      },
      {
        step_order: 5,
        step_type: "Decision",
        name: "Ransomware Confirmed?",
        action_key: "decision.ransomware_confirmed",
        connector_name: "SOAR Engine",
        config: {},
        condition: { field: "ransomware_confidence", operator: ">=", value: 85 },
      },
      {
        step_order: 6,
        step_type: "Action",
        name: "Isolate Impacted Hosts",
        action_key: "edr.bulk_isolate_hosts",
        connector_name: "Microsoft Defender",
        config: { require_approval: true },
        condition: {},
      },
      {
        step_order: 7,
        step_type: "Action",
        name: "Notify Incident Leadership",
        action_key: "notification.incident_leadership",
        connector_name: "Webhook",
        config: { priority: "critical", include_summary: true },
        condition: {},
      },
    ],
  },
];

export function templateToPlaybookPayload(template) {
  return {
    name: template.name,
    description: `${template.description}

Template Quality:
- Maturity: ${template.maturity}
- Risk Score: ${template.riskScore}
- Approval Required: ${template.approvalRequired ? "Yes" : "No"}
- Demo Ready: ${template.demoReady ? "Yes" : "No"}
- MITRE: ${template.mitre?.map((item) => `${item.id} ${item.name}`).join(", ")}`,
    category: template.category,
    status: "Draft",
    severity: template.severity,
    trigger_type: "Template",
    trigger_source: template.connectors?.[0] || "SOAR Engine",
    is_active: true,
    version: "1.0",
    tags: [
      ...(template.tags || []),
      template.maturity,
      template.demoReady ? "demo-ready" : "advanced-demo",
      template.approvalRequired ? "approval-required" : "safe-automation",
    ],
    steps: template.steps,
  };
}