export const playbooks = [
  {
    name: "Phishing Email Triage",
    category: "Email Security",
    status: "Active",
    trigger: "Suspicious Email IOC",
    version: "v2.4",
    success: 94,
    executions: 1284,
    updated: "12 min ago",
    severity: "High",
  },
  {
    name: "Malware Containment",
    category: "Endpoint Defense",
    status: "Active",
    trigger: "EDR Malware Alert",
    version: "v3.1",
    success: 91,
    executions: 846,
    updated: "28 min ago",
    severity: "Critical",
  },
  {
    name: "Brute Force Response",
    category: "Identity Protection",
    status: "Testing",
    trigger: "Failed Login Spike",
    version: "v1.8",
    success: 87,
    executions: 632,
    updated: "1 hour ago",
    severity: "Medium",
  },
  {
    name: "Suspicious IP Enrichment",
    category: "Threat Intelligence",
    status: "Active",
    trigger: "IOC Submitted",
    version: "v2.0",
    success: 97,
    executions: 2150,
    updated: "2 hours ago",
    severity: "Medium",
  },
];