import { GitBranch, PlayCircle, ShieldAlert, Zap } from "lucide-react";

function iconForType(type) {
  if (type === "Trigger") return PlayCircle;
  if (type === "Decision") return GitBranch;
  if (type === "Action") return Zap;
  return ShieldAlert;
}

export default function AIWorkflowSteps({ steps = [] }) {
  return (
    <div className="spectra-glass-card ai-workflow-panel">
      <div className="ai-panel-header">
        <div>
          <h2>Recommended Workflow Steps</h2>
          <p>Structured automation logic generated by SpectraAI.</p>
        </div>
      </div>

      <div className="ai-workflow-steps">
        {steps.map((step, index) => {
          const Icon = iconForType(step.step_type);

          return (
            <div className="ai-workflow-step" key={`${step.name}-${index}`}>
              <div className="ai-step-number">{index + 1}</div>

              <div className="ai-step-icon">
                <Icon size={18} />
              </div>

              <div>
                <span className={`node-type ${step.step_type.toLowerCase()}`}>
                  {step.step_type}
                </span>

                <h3>{step.name}</h3>
                <p>{step.description}</p>

                <div className="queue-meta" style={{ marginTop: "10px" }}>
                  <span>{step.connector_name}</span>
                  <span>{step.action_key}</span>
                  <span>{step.timeout_seconds}s timeout</span>
                </div>
              </div>
            </div>
          );
        })}
      </div>
    </div>
  );
}