"""Add log events table

Revision ID: 40d6fa3dfbad
Revises: 7adf0ba6c0a0
Create Date: 2026-06-21 01:43:00.743436

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '40d6fa3dfbad'
down_revision: Union[str, Sequence[str], None] = '7adf0ba6c0a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('log_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('raw_log', sa.Text(), nullable=False),
    sa.Column('source_ip', sa.String(length=45), nullable=True),
    sa.Column('target_ip', sa.String(length=45), nullable=True),
    sa.Column('username', sa.String(length=100), nullable=True),
    sa.Column('attack_type', sa.String(length=100), nullable=True),
    sa.Column('severity', sa.String(length=20), nullable=True),
    sa.Column('risk_score', sa.Float(), nullable=True),
    sa.Column('analyzed', sa.Boolean(), nullable=True),
    sa.Column('alert_created', sa.Boolean(), nullable=True),
    sa.Column('processing_time_ms', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_log_events_id'), 'log_events', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_log_events_id'), table_name='log_events')
    op.drop_table('log_events')
    # ### end Alembic commands ###
