"""add threat cache table

Revision ID: b3ac055b0303
Revises: 40d6fa3dfbad
Create Date: 2026-06-22 02:44:51.040453

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b3ac055b0303'
down_revision: Union[str, Sequence[str], None] = '40d6fa3dfbad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('threat_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('indicator', sa.String(length=255), nullable=False),
    sa.Column('indicator_type', sa.String(length=50), nullable=False),
    sa.Column('risk_score', sa.Integer(), nullable=True),
    sa.Column('risk_level', sa.String(length=50), nullable=True),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_threat_cache_id'), 'threat_cache', ['id'], unique=False)
    op.create_index(op.f('ix_threat_cache_indicator'), 'threat_cache', ['indicator'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_threat_cache_indicator'), table_name='threat_cache')
    op.drop_index(op.f('ix_threat_cache_id'), table_name='threat_cache')
    op.drop_table('threat_cache')
    # ### end Alembic commands ###
