"""add ioc history fields

Revision ID: ea2f8c82c90c
Revises: b3ac055b0303
Create Date: 2026-06-22 03:44:22.259882

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea2f8c82c90c'
down_revision: Union[str, Sequence[str], None] = 'b3ac055b0303'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('threat_cache', sa.Column('lookup_count', sa.Integer(), nullable=True))
    op.add_column('threat_cache', sa.Column('first_seen', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('threat_cache', sa.Column('last_seen', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('threat_cache', 'last_seen')
    op.drop_column('threat_cache', 'first_seen')
    op.drop_column('threat_cache', 'lookup_count')
    # ### end Alembic commands ###
