import { useMemo, useState } from "react";
import {
  Activity,
  AlertTriangle,
  CheckCircle2,
  Download,
  Eye,
  FileText,
  Loader2,
  PlayCircle,
  Rocket,
  ShieldCheck,
  Sparkles,
  Trophy,
  Zap,
} from "lucide-react";

import SOAR_API from "../../../api/soarApi";
import {
  PLAYBOOK_TEMPLATES,
  templateToPlaybookPayload,
} from "../templates/playbookTemplates";

function wait(ms) {
  return new Promise((resolve) => setTimeout(resolve, ms));
}

function formatTime(value) {
  if (!value) return "Not available";

  try {
    return new Date(value).toLocaleString();
  } catch {
    return value;
  }
}

function safeName(value = "demo") {
  return value.toLowerCase().replaceAll(" ", "-").replaceAll("/", "-");
}

function downloadDemoSummary(result, events) {
  const payload = {
    generated_at: new Date().toISOString(),
    demo_result: result,
    timeline: events,
  };

  const blob = new Blob([JSON.stringify(payload, null, 2)], {
    type: "application/json",
  });

  const url = URL.createObjectURL(blob);
  const link = document.createElement("a");

  link.href = url;
  link.download = `spectrasoc-soar-demo-${safeName(
    result?.scenario?.name || "summary"
  )}.json`;

  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);

  URL.revokeObjectURL(url);
}

const DEMO_SCENARIOS = [
  {
    id: "phishing-email-triage",
    title: "Phishing Email Triage Demo",
    subtitle: "Best beginner-friendly FYP demo",
    difficulty: "Easy",
    impact: "High",
    duration: "2-3 min",
    value:
      "Shows IOC extraction, enrichment, analyst notification, and incident summary workflow.",
  },
  {
    id: "ransomware-initial-response",
    title: "Ransomware Initial Response Demo",
    subtitle: "Most impressive enterprise demo",
    difficulty: "Advanced",
    impact: "Critical",
    duration: "3-5 min",
    value:
      "Shows critical incident response, endpoint containment, approval logic, and executive impact.",
  },
  {
    id: "suspicious-ip-enrichment",
    title: "Suspicious IP Enrichment Demo",
    subtitle: "Fast threat intelligence demo",
    difficulty: "Easy",
    impact: "Medium",
    duration: "1-2 min",
    value:
      "Shows AbuseIPDB, VirusTotal, GeoIP, SIEM history, and risk summary enrichment.",
  },
];

export default function SOARDemoMode({ setSection }) {
  const [selectedScenarioId, setSelectedScenarioId] = useState(
    "phishing-email-triage"
  );
  const [running, setRunning] = useState(false);
  const [events, setEvents] = useState([]);
  const [demoResult, setDemoResult] = useState(null);
  const [error, setError] = useState("");

  const selectedScenario = useMemo(() => {
    return (
      DEMO_SCENARIOS.find((item) => item.id === selectedScenarioId) ||
      DEMO_SCENARIOS[0]
    );
  }, [selectedScenarioId]);

  const selectedTemplate = useMemo(() => {
    return (
      PLAYBOOK_TEMPLATES.find((item) => item.id === selectedScenarioId) ||
      PLAYBOOK_TEMPLATES[0]
    );
  }, [selectedScenarioId]);

  const addEvent = (title, status = "Info", details = "") => {
    setEvents((prev) => [
      {
        id: `demo-event-${Date.now()}-${Math.random()
          .toString(16)
          .slice(2)}`,
        time: new Date().toISOString(),
        title,
        status,
        details,
      },
      ...prev,
    ]);
  };

  const resetDemo = () => {
    setEvents([]);
    setDemoResult(null);
    setError("");
  };

  const runDemo = async () => {
    try {
      setRunning(true);
      setError("");
      setDemoResult(null);
      setEvents([]);

      addEvent("Demo initialized", "Success", selectedScenario.title);

      const basePayload = templateToPlaybookPayload(selectedTemplate);

      const payload = {
        ...basePayload,
        name: `${selectedTemplate.name} — FYP Demo`,
        status: "Active",
        is_active: true,
        tags: [
          ...(basePayload.tags || []),
          "fyp-demo",
          "demo-mode",
          selectedScenario.id,
        ],
        description: `${basePayload.description || ""}

Demo Mode:
- Scenario: ${selectedScenario.title}
- Presenter Value: ${selectedScenario.value}
- Generated by: SpectraSOC SOAR Demo Mode`,
      };

      addEvent("Creating demo playbook", "Info", payload.name);

      const createdPlaybook = await SOAR_API.createPlaybook(payload);

      addEvent(
        "Demo playbook created",
        "Success",
        `Playbook ID: ${createdPlaybook.id}`
      );

      await wait(500);

      addEvent("Starting backend execution", "Info", "SOAR execution engine");

      const execution = await SOAR_API.startPlaybook(createdPlaybook.id, {
        trigger_payload: {
          source: "soar_demo_mode",
          scenario: selectedScenario.title,
          template_id: selectedTemplate.id,
          demo_safe_mode: true,
        },
        trigger_source: "SOAR Demo Mode",
        started_by: "FYP Presenter",
      });

      let currentExecution = await SOAR_API.getExecution(execution.id);

      addEvent(
        "Execution started",
        "Success",
        `Execution ID: ${currentExecution.id}`
      );

      const maxIterations = Math.min(
        (selectedTemplate.steps?.length || 5) * 2 + 2,
        20
      );

      for (let index = 0; index < maxIterations; index += 1) {
        if (
          String(currentExecution.status || "").toLowerCase() === "completed" ||
          String(currentExecution.status || "").toLowerCase() === "failed"
        ) {
          break;
        }

        await wait(550);

        const updated = await SOAR_API.simulateExecutionProgress(
          currentExecution.id
        );

        currentExecution = await SOAR_API.getExecution(updated.id);

        addEvent(
          `Execution progress updated`,
          "Success",
          `${currentExecution.progress || 0}% · ${
            currentExecution.status || "Running"
          }`
        );
      }

      addEvent(
        "Demo execution completed",
        "Success",
        `${currentExecution.status} · ${currentExecution.progress || 0}%`
      );

      setDemoResult({
        scenario: selectedScenario,
        template: selectedTemplate,
        playbook: createdPlaybook,
        execution: currentExecution,
        completed_at: new Date().toISOString(),
      });
    } catch (err) {
      console.error(err);
      setError("Demo mode failed. Check backend server and SOAR API routes.");
      addEvent("Demo failed", "Failed", err?.message || "Unknown error");
    } finally {
      setRunning(false);
    }
  };

  const readiness = [
    {
      title: "Playbook Templates",
      status: "Ready",
      detail: "MITRE-mapped templates available",
    },
    {
      title: "Execution Engine",
      status: "Ready",
      detail: "Backend execution and simulation enabled",
    },
    {
      title: "Approval Workflow",
      status: "Ready",
      detail: "High-risk action approval gate added",
    },
    {
      title: "Audit Logs",
      status: "Ready",
      detail: "Analyst actions are traceable",
    },
    {
      title: "Connector Layer",
      status: "Ready",
      detail: "Mock and real placeholder connector mode available",
    },
    {
      title: "Report Export",
      status: "Ready",
      detail: "Execution and demo results can be exported",
    },
  ];

  return (
    <div className="soar-demo-mode">
      <div className="soar-demo-hero spectra-glass-card">
        <div>
          <span className="hero-chip">
            <Rocket size={15} />
            FYP Demo Mode
          </span>

          <h1>SOAR Final Demo Command Center</h1>

          <p>
            Run a polished one-click SOAR demonstration. The demo creates a
            backend playbook, starts execution, simulates progress, generates
            timeline events, and prepares a summary for your FYP presentation.
          </p>
        </div>

        <div className="soar-demo-actions">
          <button className="secondary-btn" onClick={resetDemo} disabled={running}>
            <Activity size={16} />
            Reset
          </button>

          <button
            className="secondary-btn"
            onClick={() => setSection && setSection("executions")}
          >
            <Eye size={16} />
            View Executions
          </button>

          <button
            className="primary-btn"
            onClick={runDemo}
            disabled={running}
          >
            {running ? <Loader2 size={16} /> : <PlayCircle size={16} />}
            {running ? "Running Demo..." : "Run One-Click Demo"}
          </button>
        </div>
      </div>

      {error && (
        <div className="spectra-glass-card demo-error-banner">
          <AlertTriangle size={17} />
          {error}
        </div>
      )}

      <div className="demo-scenario-grid">
        {DEMO_SCENARIOS.map((scenario) => (
          <button
            key={scenario.id}
            className={`demo-scenario-card spectra-glass-card ${
              selectedScenarioId === scenario.id ? "active" : ""
            }`}
            onClick={() => setSelectedScenarioId(scenario.id)}
            disabled={running}
          >
            <div className="scenario-icon">
              {scenario.impact === "Critical" ? (
                <Zap size={20} />
              ) : (
                <ShieldCheck size={20} />
              )}
            </div>

            <div>
              <h3>{scenario.title}</h3>
              <p>{scenario.subtitle}</p>
            </div>

            <div className="scenario-meta">
              <span>{scenario.difficulty}</span>
              <span>{scenario.impact}</span>
              <span>{scenario.duration}</span>
            </div>

            <small>{scenario.value}</small>
          </button>
        ))}
      </div>

      <div className="demo-main-grid">
        <div className="spectra-glass-card demo-readiness-card">
          <div className="demo-section-title">
            <div>
              <span className="hero-chip">
                <Trophy size={15} />
                Final SOAR Readiness
              </span>

              <h2>Enterprise Readiness Checklist</h2>
            </div>

            <span className="readiness-score">6 / 6 Ready</span>
          </div>

          <div className="demo-readiness-list">
            {readiness.map((item) => (
              <div className="demo-readiness-row" key={item.title}>
                <CheckCircle2 size={16} />

                <div>
                  <b>{item.title}</b>
                  <p>{item.detail}</p>
                </div>

                <span>{item.status}</span>
              </div>
            ))}
          </div>
        </div>

        <div className="spectra-glass-card demo-result-card">
          <div className="demo-section-title">
            <div>
              <span className="hero-chip">
                <Sparkles size={15} />
                Demo Output
              </span>

              <h2>Latest Demo Result</h2>
            </div>

            <button
              className="secondary-btn"
              disabled={!demoResult}
              onClick={() => downloadDemoSummary(demoResult, events)}
            >
              <Download size={16} />
              Export Summary
            </button>
          </div>

          {!demoResult ? (
            <div className="demo-empty-result">
              <FileText size={24} />
              <b>No demo run yet</b>
              <p>
                Select a scenario and run the one-click demo to generate a
                backend playbook execution.
              </p>
            </div>
          ) : (
            <div className="demo-result-details">
              <div>
                <span>Scenario</span>
                <b>{demoResult.scenario.title}</b>
              </div>

              <div>
                <span>Playbook</span>
                <b>{demoResult.playbook.name}</b>
              </div>

              <div>
                <span>Execution Status</span>
                <b>{demoResult.execution.status}</b>
              </div>

              <div>
                <span>Progress</span>
                <b>{demoResult.execution.progress || 0}%</b>
              </div>

              <div>
                <span>Completed At</span>
                <b>{formatTime(demoResult.completed_at)}</b>
              </div>
            </div>
          )}
        </div>
      </div>

      <div className="spectra-glass-card demo-timeline-card">
        <div className="demo-section-title">
          <div>
            <span className="hero-chip">
              <Activity size={15} />
              Demo Timeline
            </span>

            <h2>Live Presentation Timeline</h2>
          </div>

          <span>{events.length} events</span>
        </div>

        {events.length === 0 ? (
          <div className="demo-empty-timeline">
            <Activity size={22} />
            <p>Timeline events will appear when the demo starts.</p>
          </div>
        ) : (
          <div className="demo-timeline-list">
            {events.map((event) => (
              <div
                className={`demo-timeline-row ${String(event.status).toLowerCase()}`}
                key={event.id}
              >
                <div className="demo-timeline-icon">
                  {event.status === "Failed" ? (
                    <AlertTriangle size={15} />
                  ) : (
                    <CheckCircle2 size={15} />
                  )}
                </div>

                <div>
                  <h3>{event.title}</h3>
                  <p>{event.details}</p>
                  <span>{formatTime(event.time)}</span>
                </div>
              </div>
            ))}
          </div>
        )}
      </div>

      <div className="spectra-glass-card demo-final-note">
        <ShieldCheck size={18} />

        <div>
          <b>SOAR module final status</b>
          <p>
            Your SOAR module now has dashboard, playbooks, templates, visual
            builder, execution engine, approvals, audit logs, connector testing,
            versioning, reporting, AI builder, settings, and presentation-ready
            demo mode.
          </p>
        </div>
      </div>
    </div>
  );
}